# Generated by Django 6.0.6 on 2026-06-09 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік видання')),
                ('description', models.TextField(blank=True, verbose_name='Опис/Рецензія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
