# Generated by Django 5.2.15 on 2026-06-12 11:57

import books.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Ім’я автора')),
                ('biography', models.TextField(blank=True, verbose_name='Біографія')),
                ('website', models.URLField(blank=True, verbose_name='Вебсайт')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='books_autho_name_5aec2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Назва книги')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN-13')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Видавництво')),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рік видання')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість сторінок')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Мова')),
                ('description', models.TextField(blank=True, verbose_name='Опис книги')),
                ('cover_image', models.ImageField(blank=True, default='', help_text='JPG, JPEG, PNG або WEBP. Максимальний розмір — 5 МБ.', max_length=255, upload_to='book_covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), books.models.validate_cover_file_size], verbose_name='Файл обкладинки')),
                ('cover_url', models.URLField(blank=True, help_text='Використовується, якщо файл обкладинки не завантажено.', verbose_name='Зовнішнє посилання на обкладинку')),
                ('series_name', models.CharField(blank=True, max_length=255, verbose_name='Серія книг')),
                ('series_number', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Номер у серії')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to=settings.AUTH_USER_MODEL, verbose_name='Хто додав книгу')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Автори')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='books.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('want_to_read', 'Хочу прочитати'), ('reading', 'Читаю'), ('paused', 'Відкладено'), ('completed', 'Прочитано'), ('dropped', 'Не дочитано')], default='want_to_read', max_length=20, verbose_name='Статус читання')),
                ('book_format', models.CharField(choices=[('paper', 'Паперова книга'), ('ebook', 'Електронна книга'), ('audiobook', 'Аудіокнига'), ('other', 'Інший формат')], default='paper', max_length=20, verbose_name='Формат книги')),
                ('visibility', models.CharField(choices=[('private', 'Приватна'), ('friends', 'Для друзів'), ('public', 'Публічна')], default='private', max_length=20, verbose_name='Видимість')),
                ('current_page', models.PositiveIntegerField(default=0, verbose_name='Поточна сторінка')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогрес читання')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Особиста оцінка')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Улюблена книга')),
                ('is_owned', models.BooleanField(default=True, verbose_name='Є у власності')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата початку читання')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Дата завершення читання')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Книга в бібліотеці',
                'verbose_name_plural': 'Книги в бібліотеці',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('note_type', models.CharField(choices=[('note', 'Звичайна нотатка'), ('summary', 'Конспект'), ('idea', 'Власна думка'), ('question', 'Питання'), ('todo', 'Потрібно опрацювати')], default='note', max_length=20, verbose_name='Тип нотатки')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст нотатки')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сторінка')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закріплена')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.libraryentry', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Нотатка',
                'verbose_name_plural': 'Нотатки',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сторінка')),
                ('position', models.CharField(blank=True, help_text='Наприклад: 35%, глава 4 або 01:24:30', max_length=100, verbose_name='Позиція в електронній або аудіокнизі')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Назва закладки')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.libraryentry', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['page', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=50, verbose_name='Назва тегу')),
                ('color', models.CharField(blank=True, help_text='Наприклад: #3498db', max_length=20, verbose_name='Колір')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Особистий тег',
                'verbose_name_plural': 'Особисті теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='books.libraryentry', verbose_name='Запис бібліотеки')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='books.personaltag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег книги',
                'verbose_name_plural': 'Теги книг',
            },
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='library_entries', through='books.LibraryEntryTag', to='books.personaltag', verbose_name='Особисті теги'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('text', models.TextField(verbose_name='Текст цитати')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сторінка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Улюблена цитата')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.libraryentry', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитати',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('started_at', models.DateTimeField(verbose_name='Початок читання')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення читання')),
                ('start_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Початкова сторінка')),
                ('end_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кінцева сторінка')),
                ('note', models.TextField(blank=True, verbose_name='Коментар до сесії')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.libraryentry', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Сесія читання',
                'verbose_name_plural': 'Сесії читання',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок рецензії')),
                ('text', models.TextField(verbose_name='Текст рецензії')),
                ('contains_spoilers', models.BooleanField(default=False, verbose_name='Містить спойлери')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікована')),
                ('library_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.libraryentry', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Рецензія',
                'verbose_name_plural': 'Рецензії',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Назва полиці')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічна полиця')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_shelves', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Книжкова полиця',
                'verbose_name_plural': 'Книжкові полиці',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_items', to='books.libraryentry', verbose_name='Книга')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='books.shelf', verbose_name='Полиця')),
            ],
            options={
                'verbose_name': 'Книга на полиці',
                'verbose_name_plural': 'Книги на полицях',
            },
        ),
        migrations.AddField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='shelves', through='books.ShelfItem', to='books.libraryentry', verbose_name='Книги'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Ім’я для відображення')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Посилання на аватар')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Часовий пояс')),
                ('bio', models.TextField(blank=True, verbose_name='Про користувача')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['published_year'], name='books_book_publish_9a145c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn13'], name='books_book_isbn13_826edb_idx'),
        ),
        migrations.AddIndex(
            model_name='booknote',
            index=models.Index(fields=['library_entry', '-updated_at'], name='books_bookn_library_bd5efa_idx'),
        ),
        migrations.AddConstraint(
            model_name='personaltag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_personal_tag_per_user'),
        ),
        migrations.AddConstraint(
            model_name='libraryentrytag',
            constraint=models.UniqueConstraint(fields=('library_entry', 'tag'), name='unique_tag_for_library_entry'),
        ),
        migrations.AddIndex(
            model_name='libraryentry',
            index=models.Index(fields=['user', 'status'], name='books_libra_user_id_94fba9_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryentry',
            index=models.Index(fields=['user', 'is_favorite'], name='books_libra_user_id_1495bc_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryentry',
            index=models.Index(fields=['user', '-updated_at'], name='books_libra_user_id_be370d_idx'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_book_in_user_library'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='library_progress_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='library_rating_between_1_and_5'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['library_entry', '-started_at'], name='books_readi_library_7fde59_idx'),
        ),
        migrations.AddConstraint(
            model_name='shelfitem',
            constraint=models.UniqueConstraint(fields=('shelf', 'library_entry'), name='unique_book_on_shelf'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_shelf_name_per_user'),
        ),
    ]
